### ISSUE TITLE
Can't get status from covers

### ISSUE THREAD

**Issue by Caleche317** [CyrilP/hass-deltadore-tydom-component#117]
## System Information

version | core-2024.9.0
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 5.15.0-119-generic
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 9
views | 4
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 28 août 2024 à 01:00
-- | --
current_recorder_run | 5 septembre 2024 à 21:11
estimated_db_size | 124.29 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hello,

I just installed your module for controlling covers and getting power info from a TYWATT2000.

I can control covers correctly but I need to restart the integration to get their new position. If I don't, the position stay unchanged. If the position is changed using the wall switch Home assistant doesn't get the new position unless I restart the integration.

Sometimes restarting the integration is not enough, I have to do it several times to get the positions correctly.

Not sure if its related but the integration doesn't see the TYWATT2000, but I'm not sure if it's a part of the same problem or if it's just because it's not supported yet.

I don't think it's the same issue as the [#69](https://github.com/CyrilP/hass-deltadore-tydom-component/issues/69) because on it's issue, it usually works but often disconnect. In my case I'm perfectly connected in local, can perfectly drive the covers anytime but never get the position.

Not sure if this can help but I installed your integration because I've had trouble with the TYDOM2MQTT which doesn't parse my hardware's messages anymore (not sure what happened not what the problem is, log are not really helpfull). So maybe it's a message parsing problem too...

PS : for the TYWATT2000 part, if it's just because it's not supported yet, I'd be glad to help you in any way (I'm not a coding guru but I can write/understand simple python and as I own the hardware, maybe there's something I can do.)

In advance, thank you so much for your help !

### Reproduction steps

1. Read the cover position (example : 0)
2. Change the cover position (example : 0 to 100).
3. Read the cover position : It's still 0, even if the cover position has changed/
4. Restart the integration
5. Read the cover position : It's now 100. (sometimes it seems needed to restart the integration several times).

### Debug logs

```text
2024-09-05 21:11:22.776 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f2e0e4560d0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'deltadore_tydom' at custom_components/deltadore_tydom/tydom/tydom_client.py, line 215: sslcontext = ssl.create_default_context() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/CyrilP/hass-deltadore-tydom-component/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/deltadore_tydom/__init__.py", line 63, in async_setup_entry
    connection = await tydom_hub.connect()
  File "/config/custom_components/deltadore_tydom/hub.py", line 110, in connect
    connection = await self._tydom_client.async_connect()
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 215, in async_connect
    sslcontext = ssl.create_default_context()

2024-09-05 21:11:22.816 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "sizes". Check lines 40 and 57
2024-09-05 21:11:22.816 WARNING (SyncWorker_5) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "frontend". Check lines 5 and 60
2024-09-05 21:11:23.048 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/frontend", "/config/custom_components/hacs/hacs_frontend", False)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 54: hass.http.register_static_path(f"{URL_BASE}/frontend", locate_dir(), cache_headers=False), please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:23.051 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles/iconset.js", "/config/custom_components/hacs/iconset.js", True)])`; This function will be removed in 2025.7 at custom_components/hacs/frontend.py, line 57: hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:23.054 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:23.058 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' calls hass.http.register_static_path which is deprecated because it does blocking I/O in the event loop, instead call `await hass.http.async_register_static_paths([StaticPathConfig("/hacsfiles", "/config/www/community", True)])`; This function will be removed in 2025.7 at custom_components/hacs/base.py, line 1162: self.hass.http.register_static_path(, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:26.363 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received 
2024-09-05 21:11:26.404 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/hub.py", line 147, in setup
    await self.create_ha_device(device)
  File "/config/custom_components/deltadore_tydom/hub.py", line 200, in create_ha_device
    ha_device = HaClimate(device, self._hass)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/ha_entities.py", line 660, in __init__
    if  "NORMAL" in self._device._metadata["thermicLevel"] or "AUTO" in self._device._metadata["thermicLevel"]:
                    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'thermicLevel'
2024-09-05 21:11:29.715 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 630: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:29.946 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:30.148 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:30.247 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:30.257 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:30.526 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:31.864 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:31.917 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:31.964 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:31.976 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:31.979 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.051 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.059 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.061 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.160 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.424 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.521 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:32.658 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:33.001 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:33.171 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:33.368 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:11:33.502 WARNING (MainThread) [homeassistant.util.json] json_loads was called from hacs, this is a deprecated function which will be removed in HA Core 2025.8. Use homeassistant.util.json.json_loads instead, please create a bug report at https://github.com/hacs/integration/issues
2024-09-05 21:12:59.335 ERROR (MainThread) [homeassistant.components.xiaomi_ble] C4:7C:8D:6D:C7:30: Bluetooth error whilst polling: C4:7C:8D:6D:C7:30 - C4:7C:8D:6D:C7:30: Failed to connect after 4 attempt(s): TimeoutError
2024-09-05 21:13:03.856 ERROR (MainThread) [homeassistant.components.xiaomi_ble] 5C:85:7E:12:F4:88: Bluetooth error whilst polling: 5C:85:7E:12:F4:88 - 5C:85:7E:12:F4:88: Failed to connect after 4 attempt(s): TimeoutError
2024-09-05 21:15:10.324 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.begonia_rex_total_ppfd_mol_integral (mol/s⋅m²s) cannot be converted to the unit of previously compiled statistics (mol/d⋅m²). Generation of long term statistics will be suppressed unless the unit changes back to mol/d⋅m² or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-09-05 21:15:10.324 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.begonia_rex_dli (mol/s⋅m²s) cannot be converted to the unit of previously compiled statistics (mol/d⋅m²). Generation of long term statistics will be suppressed unless the unit changes back to mol/d⋅m² or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-09-05 21:15:10.325 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.monstera_deliciosa_total_ppfd_mol_integral (mol/s⋅m²s) cannot be converted to the unit of previously compiled statistics (mol/d⋅m²). Generation of long term statistics will be suppressed unless the unit changes back to mol/d⋅m² or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-09-05 21:15:10.325 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.monstera_deliciosa_dli (mol/s⋅m²s) cannot be converted to the unit of previously compiled statistics (mol/d⋅m²). Generation of long term statistics will be suppressed unless the unit changes back to mol/d⋅m² or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-09-05 22:18:51.916 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /ping)
2024-09-05 22:18:53.208 DEBUG (MainThread) [custom_components.deltadore_tydom] response status : 401
headers : <CIMultiDictProxy('Connection': 'close', 'WWW-Authenticate': 'Digest realm="Protected Area", qop="auth", nonce="be0a0d7e0d843467c3c07180adf9f108", opaque="c6696e782cd029e47677b4a6a273c670"', 'Content-Type': 'text/html')>
content : <!doctype html>
<html>
<head><title>Error 401</title></head>
<body>
<h2>Error 401</h2>
<p>Authorization required</p>
</body>
</html>

2024-09-05 22:19:06.710 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (PUT device data [{"name":"position","value":"20"}])
2024-09-05 22:19:07.996 DEBUG (MainThread) [custom_components.deltadore_tydom] response status : 401
headers : <CIMultiDictProxy('Connection': 'close', 'WWW-Authenticate': 'Digest realm="Protected Area", qop="auth", nonce="b547794442d02550d942928c36605631", opaque="cb1e1a36ffb5ad0eb69b44a8bd83a2c0"', 'Content-Type': 'text/html')>
content : <!doctype html>
<html>
<head><title>Error 401</title></head>
<body>
<h2>Error 401</h2>
<p>Authorization required</p>
</body>
</html>

2024-09-05 22:19:10.202 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyDistrib&period=YEAR&periodOffset=0&src=ELEC)
2024-09-05 22:19:10.204 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyInstant&unit=ELEC_A&reset=false)
2024-09-05 22:19:10.205 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false)
2024-09-05 22:19:10.206 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false)
2024-09-05 22:19:10.207 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_HOTWATER&reset=false)
2024-09-05 22:19:10.207 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_OUTLET&reset=false)
2024-09-05 22:19:10.208 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_OTHER&reset=false)
2024-09-05 22:19:10.208 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=TEMP_INDOOR&reset=false)
2024-09-05 22:19:10.208 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=TEMP_OUTDOOR&reset=false)
2024-09-05 22:19:25.542 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (GET /ping)
2024-09-05 22:19:26.744 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (PUT device data [{"name":"position","value":"0"}])
2024-09-05 22:19:26.818 DEBUG (MainThread) [custom_components.deltadore_tydom] response status : 401
headers : <CIMultiDictProxy('Connection': 'close', 'WWW-Authenticate': 'Digest realm="Protected Area", qop="auth", nonce="97582b71e67257234361a0e974cbe649", opaque="6bb5f1b62d2207aebb680872d96554d0"', 'Content-Type': 'text/html')>
content : <!doctype html>
<html>
<head><title>Error 401</title></head>
<body>
<h2>Error 401</h2>
<p>Authorization required</p>
</body>
</html>

2024-09-05 22:19:28.072 DEBUG (MainThread) [custom_components.deltadore_tydom] response status : 401
headers : <CIMultiDictProxy('Connection': 'close', 'WWW-Authenticate': 'Digest realm="Protected Area", qop="auth", nonce="061bffa9ffe2327b9fffd1e8a5be5d4c", opaque="afb1f66648c84084974cb09a1d74399b"', 'Content-Type': 'text/html')>
content : <!doctype html>
<html>
<head><title>Error 401</title></head>
<body>
<h2>Error 401</h2>
<p>Authorization required</p>
</body>
</html>

2024-09-05 22:19:31.140 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (PUT device data [{"name":"position","value":"0"}])
2024-09-05 22:19:32.086 DEBUG (MainThread) [custom_components.deltadore_tydom] Sending message to tydom (PUT device data [{"name":"position","value":"0"}])
```

**Comment by Caleche317** [comment]
Ok, so I tried some things.

It seems that all the problems came from this : 

` 2024-09-08 23:59:14.518 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/hub.py", line 147, in setup
    await self.create_ha_device(device)
  File "/config/custom_components/deltadore_tydom/hub.py", line 200, in create_ha_device
    ha_device = HaClimate(device, self._hass)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/ha_entities.py", line 660, in __init__
    #if  "NORMAL" in self._device._metadata["thermicLevel"] or "AUTO" in self._device._metadata["thermicLevel"]:
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'thermicLevel'
`

I messed a bit with your code and commented lines 660 and 661 of ha_entities.py and the 401 error are not shown anymore...

I don't know at all what these lines are doing... but I have my covers working fine...

Concerning my TYWATT 2000 it seems to be seen partially now but I only have the temperature from the outside temp probe. I don't have the Energy data...

It seems to be seen somehow by your code but not used correctly because I see this

'
2024-09-09 00:04:06.394 DEBUG (MainThread) [custom_components.deltadore_tydom] config_data device parsed : 1601804653_1601804653 - Product hvac 1
2024-09-09 00:04:06.394 DEBUG (MainThread) [custom_components.deltadore_tydom] config_data device parsed : 1601804654_1601804653 - Consommation
'

this

'
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] parse_cmeta_data : [{'id': 1595616559, 'endpoints': [{'id': 1595616559, 'error': 0, 'cmetadata': []}]}, {'id': 1595616957, 'endpoints': [{'id': 1595616957, 'error': 0, 'cmetadata': []}]}, {'id': 1595617240, 'endpoints': [{'id': 1595617240, 'error': 0, 'cmetadata': []}]}, {'id': 1595617425, 'endpoints': [{'id': 1595617425, 'error': 0, 'cmetadata': []}]}, {'id': 1595620943, 'endpoints': [{'id': 1595620943, 'error': 0, 'cmetadata': []}]}, {'id': 1595621339, 'endpoints': [{'id': 1595621339, 'error': 0, 'cmetadata': []}]}, {'id': 1595621538, 'endpoints': [{'id': 1595621538, 'error': 0, 'cmetadata': []}]}, {'id': 1595621628, 'endpoints': [{'id': 1595621628, 'error': 0, 'cmetadata': []}]}, {'id': 1596476182, 'endpoints': [{'id': 1596476182, 'error': 0, 'cmetadata': []}]}, {'id': 1596476354, 'endpoints': [{'id': 1596476354, 'error': 0, 'cmetadata': []}]}, {'id': 1601804653, 'endpoints': [{'id': 1601804653, 'error': 0, 'cmetadata': []}, {'id': 1601804654, 'error': 0, 'cmetadata': [{'name': 'energyHisto', 'permission': 'r', 'parameters': [{'name': 'period', 'type': 'string', 'enum_values': ['YEARS', 'YEAR', 'MONTH', 'DAY']}, {'name': 'periodOffset', 'type': 'numeric', 'min': 0, 'max': 31}, {'name': 'dest', 'type': 'string', 'enum_values': ['ELEC_TOTAL', 'ELEC_HEATING', 'ELEC_HOTWATER', 'ELEC_OUTLET', 'ELEC_OTHER', 'TEMP_INDOOR', 'TEMP_OUTDOOR']}]}, {'name': 'energyDistrib', 'permission': 'r', 'parameters': [{'name': 'period', 'type': 'string', 'enum_values': ['YEAR', 'MONTH']}, {'name': 'periodOffset', 'type': 'numeric', 'min': 0, 'max': 31}, {'name': 'src', 'type': 'string', 'enum_values': ['ELEC']}]}, {'name': 'energyInstant', 'permission': 'r', 'parameters': [{'name': 'unit', 'type': 'string', 'enum_values': ['ELEC_A']}, {'name': 'reset', 'type': 'boolean'}]}, {'name': 'energyIndex', 'permission': 'r', 'parameters': [{'name': 'dest', 'type': 'string', 'enum_values': ['ELEC_TOTAL', 'ELEC_HEATING', 'ELEC_HOTWATER', 'ELEC_OUTLET', 'ELEC_OTHER', 'TEMP_INDOOR', 'TEMP_OUTDOOR']}, {'name': 'reset', 'type': 'boolean'}]}]}]}]
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyDistrib&period=YEAR&periodOffset=0&src=ELEC
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyInstant&unit=ELEC_A&reset=false
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_HOTWATER&reset=false
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_OUTLET&reset=false
2024-09-09 00:04:06.512 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=ELEC_OTHER&reset=false
2024-09-09 00:04:06.513 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=TEMP_INDOOR&reset=false
2024-09-09 00:04:06.513 DEBUG (MainThread) [custom_components.deltadore_tydom] Add poll device : /devices/1601804653/endpoints/1601804654/cdata?name=energyIndex&dest=TEMP_OUTDOOR&reset=false
'

and this

'
2024-09-09 00:04:06.800 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595616559, endpoint=1595616559, name=Salon, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595616957, endpoint=1595616957, name=Séjour, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595617240, endpoint=1595617240, name=Cuisine, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595617425, endpoint=1595617425, name=Evier, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595620943, endpoint=1595620943, name=Porte Fenêtre, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595621339, endpoint=1595621339, name=Bureau, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595621538, endpoint=1595621538, name=Chambre 1, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1595621628, endpoint=1595621628, name=Dressing, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1596476182, endpoint=1596476182, name=Chambre 2, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1596476354, endpoint=1596476354, name=Chambre 3, type=shutter)
2024-09-09 00:04:06.801 INFO (MainThread) [custom_components.deltadore_tydom] Device update (id=1601804653, endpoint=1601804653, name=Product hvac 1, type=electric)
'
Note that in this last part there is "Product hvac 1" but not "Consommation" (this is not a copy/paste mistake)

I'm already happy with my shutters but I suppose my # commenting the lines will disapear on your next update. Could you please what's wrong with this ?

and maybe if you have more time, what's wring with the energy meter ?

Thanks in advance for your help.

**Comment by CyrilP** [comment]
the error with thermicLevel should now be fixed, it will be available in the next release.
can you please provide more logs about the TYWATT 2000 if you still miss some values ?
create a new issue for that
