### ISSUE TITLE
localtuya' accesses hass.helpers.service

### ISSUE THREAD

**Issue by Renz1982** [CyrilP/hass-deltadore-tydom-component#143]
## System Information

version | core-2024.12.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.62-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1494
Downloaded Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.0
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.0 GB
disk_used | 6.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (6.6.1), Terminal & SSH (9.16.0), Get HACS (1.3.1), File editor (5.8.0), Mosquitto broker (6.4.1), Home-Assistant-Matter-Hub (3.0.0-alpha.58)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 22. Dezember 2024 um 11:35
-- | --
current_recorder_run | 30. Dezember 2024 um 19:49
estimated_db_size | 242.86 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Logger: homeassistant.helpers.frame
Quelle: helpers/frame.py:324
Erstmals aufgetreten: 19:49:55 (2 Vorkommnisse)
Zuletzt protokolliert: 22:22:45

Detected that custom integration 'localtuya' accesses hass.helpers.service, which should be updated to import functions used from service directly at custom_components/localtuya/__init__.py, line 165: hass.helpers.service.async_register_admin_service(. This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/rospogrigio/localtuya/issues
Detected that custom integration 'deltadore_tydom' sets option flow config_entry explicitly, which is deprecated at custom_components/deltadore_tydom/config_flow.py, line 603: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/CyrilP/hass-deltadore-tydom-component/issues

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
see diagnostics dump
```

### Diagnostics dump

2024-12-30 19:49:48.072 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:48.075 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deltadore_tydom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:48.076 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration foxess which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:48.078 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration livisi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:48.080 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:48.081 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 19:49:55.211 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'localtuya' accesses hass.helpers.service, which should be updated to import functions used from service directly at custom_components/localtuya/__init__.py, line 165: hass.helpers.service.async_register_admin_service(. This will stop working in Home Assistant 2025.5, please create a bug report at https://github.com/rospogrigio/localtuya/issues
2024-12-30 19:49:55.394 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_ARMED_AWAY was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'deltadore_tydom' custom integration
2024-12-30 19:49:55.400 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_ARMED_HOME was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'deltadore_tydom' custom integration
2024-12-30 19:49:55.406 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_DISARMED was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'deltadore_tydom' custom integration
2024-12-30 19:49:55.411 WARNING (ImportExecutor_0) [homeassistant.const] STATE_ALARM_TRIGGERED was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'deltadore_tydom' custom integration
2024-12-30 19:49:55.510 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7f87a4d5b0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'deltadore_tydom' at custom_components/deltadore_tydom/tydom/tydom_client.py, line 215: sslcontext = ssl.create_default_context() (offender: /usr/local/lib/python3.13/ssl.py, line 722: context.load_default_certs(purpose)), please create a bug report at https://github.com/CyrilP/hass-deltadore-tydom-component/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 708, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 679, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2027, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 788, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_setup
    await self.__async_setup_with_context(hass, integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/deltadore_tydom/__init__.py", line 63, in async_setup_entry
    connection = await tydom_hub.connect()
  File "/config/custom_components/deltadore_tydom/hub.py", line 110, in connect
    connection = await self._tydom_client.async_connect()
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 215, in async_connect
    sslcontext = ssl.create_default_context()

2024-12-30 19:49:55.579 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:00.275 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.sensor_netzbezug (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using state class 'total_increasing' which is impossible considering device class ('power') it is using; expected None or one of 'measurement'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2024-12-30 19:50:00.440 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:00.531 WARNING (MainThread) [homeassistant.components.fan] Entity None (<class 'custom_components.midea_dehumidifier_lan.fan.DehumidiferFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan/issues
2024-12-30 19:50:00.532 WARNING (MainThread) [homeassistant.components.fan] Entity None (<class 'custom_components.midea_dehumidifier_lan.fan.DehumidiferFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/nbogojevic/homeassistant-midea-air-appliances-lan/issues
2024-12-30 19:50:03.550 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform foxess is taking over 10 seconds.
2024-12-30 19:50:05.439 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:10.441 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:14.070 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received 
2024-12-30 19:50:15.447 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:20.450 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:25.451 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:30.457 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:35.462 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:40.464 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:45.470 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae5
2024-12-30 19:50:50.473 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf6512bba95a63ead8xae

**Comment by Renz1982** [comment]
After Update to newest HA Version it comes following Log:

Logger: homeassistant.const
Quelle: helpers/deprecation.py:222
Erstmals aufgetreten: 22:53:06 (4 Vorkommnisse)
Zuletzt protokolliert: 22:53:06

STATE_ALARM_ARMED_AWAY was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_AWAY instead, please report it to the author of the 'deltadore_tydom' custom integration
STATE_ALARM_ARMED_HOME was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.ARMED_HOME instead, please report it to the author of the 'deltadore_tydom' custom integration
STATE_ALARM_DISARMED was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.DISARMED instead, please report it to the author of the 'deltadore_tydom' custom integration
STATE_ALARM_TRIGGERED was used from deltadore_tydom, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'deltadore_tydom' custom integration

**Comment by Sleinous** [comment]
Hi @Renz1982, the Delta Dore warnings reported here have now been resolved:
the deprecated alarm constants were replaced by AlarmControlPanelState in #156;
the blocking SSL context creation was moved outside the event loop in #158;
the deprecated options-flow config-entry assignment was corrected in #241.
These corrections are all included in the current v0.28 release.
The localtuya warning shown in the original report belongs to a separate integration and must be handled by that project.
I am therefore closing this issue as resolved. Thank you for reporting it.
