### ISSUE TITLE
Intégration

### ISSUE THREAD

**Issue by Flanash** [CyrilP/hass-deltadore-tydom-component#68]
### System Health details

Core
2024.4.0
Supervisor
2024.03.1
Operating System
12.2.rc1
Interface utilisateur
20240403.1

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Bonjour, 
Merci pour cette intégration de tydom!
Je suis ultra débutant dans HA, et pas trop de connaissances en développement.
J'avais réussi à mettre l'intégration et je voyais tous mes équipements dedans mais suite à une mauvaise manip j'ai du réinstallé ma vm, tout refaire et depuis je ne vois que ma box tydom et plus aucun équipement.
J'ai essayé plusieurs release de HA et de votre intégration mais j'ai toujours les mêmes erreurs!
Si vous pouvez m'aiguiller! merci beaucoup!

### Reproduction steps

1.création du repertoire ccustom_components
2. copie du repertoire Detadore_tydom dedans
3.Redemarrage de HA
4. Ajout de l'integration et login

### Debug logs

```text
2024-04-05 00:33:26.937 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration deltadore_tydom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-05 00:34:14.993 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown usage : unknown for device_id 1701507948, uid 1711577824_1701507948
2024-04-05 00:34:15.004 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/hub.py", line 132, in setup
    await self.create_ha_device(device)
  File "/config/custom_components/deltadore_tydom/hub.py", line 185, in create_ha_device
    ha_device = HaClimate(device, self._hass)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/ha_entities.py", line 633, in __init__
    if "min" in self._device._metadata["setpoint"]:
                ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'setpoint'
2024-04-05 00:39:18.981 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyInstant&unit=ELEC_A&reset=false
2024-04-05 00:39:18.983 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyDistrib&period=YEAR&periodOffset=0&src=ELEC
2024-04-05 00:39:18.983 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyInstant&unit=ELEC_A&reset=false
2024-04-05 00:39:18.984 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false
2024-04-05 00:39:18.986 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false
2024-04-05 00:39:18.987 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_COOLING&reset=false
2024-04-05 00:39:18.988 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HOTWATER&reset=false
2024-04-05 00:39:18.989 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OUTLET&reset=false
2024-04-05 00:39:18.990 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OTHER&reset=false
2024-04-05 00:44:24.013 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false
2024-04-05 00:44:24.015 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyDistrib&period=YEAR&periodOffset=0&src=ELEC
2024-04-05 00:44:24.016 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyInstant&unit=ELEC_A&reset=false
2024-04-05 00:44:24.017 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false
2024-04-05 00:44:24.019 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false
2024-04-05 00:44:24.020 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_COOLING&reset=false
2024-04-05 00:44:24.021 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HOTWATER&reset=false
2024-04-05 00:44:24.021 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OUTLET&reset=false
2024-04-05 00:44:24.022 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OTHER&reset=false
2024-04-05 00:49:30.290 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false
2024-04-05 00:49:30.292 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyDistrib&period=YEAR&periodOffset=0&src=ELEC
2024-04-05 00:49:30.294 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyInstant&unit=ELEC_A&reset=false
2024-04-05 00:49:30.295 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_TOTAL&reset=false
2024-04-05 00:49:30.296 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HEATING&reset=false
2024-04-05 00:49:30.297 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_COOLING&reset=false
2024-04-05 00:49:30.298 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_HOTWATER&reset=false
2024-04-05 00:49:30.298 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OUTLET&reset=false
2024-04-05 00:49:30.299 ERROR (MainThread) [custom_components.deltadore_tydom] poll device data /devices/1701507948/endpoints/1701507950/cdata?name=energyIndex&dest=ELEC_OTHER&reset=false
```

**Comment by Flanash** [comment]
[home-assistant_deltadore_tydom_2024-04-04T23-10-49.899Z.log](https://github.com/CyrilP/hass-deltadore-tydom-component/files/14881319/home-assistant_deltadore_tydom_2024-04-04T23-10-49.899Z.log)

**Comment by CyrilP** [comment]
Bonjour, 
c'est un problème que quelqu'un a déjà rencontré avec une calybox, la correction est disponible dans la dernière version beta (v0.6-dev7). si vous utilisez HACS pour l'installer, il faut cocher "Afficher les versions bêta" ou la télécharger sur github.

**Comment by Flanash** [comment]
Bonsoir,
Merci de votre réponse!
<img width="1115" alt="HACS Beta" src="https://github.com/CyrilP/hass-deltadore-tydom-component/assets/165405576/57eb3729-be71-45ad-a889-f8637def1087">

J'ai activé la version bêta de HACS, je ne trouve pas l'integation

et quand je prend sur Git hub je ne trouve pas l'intration
<img width="370" alt="Delta" src="https://github.com/CyrilP/hass-deltadore-tydom-component/assets/165405576/8dcefe3b-ff5a-47bd-98f8-a5624b6ab8b9">
<img width="221" alt="v06-dev7" src="https://github.com/CyrilP/hass-deltadore-tydom-component/assets/165405576/0ad0cc5c-e4de-40f2-a3b7-0ba440e787c5">

Merci de votre aide.

**Comment by CyrilP** [comment]
Ça fonctionne maintenant ?

**Comment by Flanash** [comment]
Oui parfaitement! Encore merci pour votre travail!
