### ISSUE TITLE
Unknown message type received

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [CyrilP/hass-deltadore-tydom-component#92]
## System Information

version | core-2024.5.5
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.29-haos
arch | x86_64
timezone | Europe/Vienna
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1397
Downloaded Repositories | 21
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.05.1
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 62.3 GB
disk_used | 9.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Terminal & SSH (9.14.0), Studio Code Server (5.15.0), OneDrive Backup (2.3.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 5
-- | --
resources | 12
views | 11
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 21. Mai 2024 um 09:04
-- | --
current_recorder_run | 27. Mai 2024 um 10:24
estimated_db_size | 1219.47 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

i see the following warning:
2024-05-27 11:34:59.815 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received 
2024-05-27 11:43:15.281 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received {"mode": "STOP", "support": ["STOP", "HEATING"]}
2024-05-27 11:44:59.816 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received 
2024-05-27 11:48:02.804 WARNING (MainThread) [custom_components.deltadore_tydom] Unknown message type received {"productName": "TYDOM HOME", "mac": "001A250816C4", "config": "prod", "bddEmpty": false, "bddStatus": 0, "apiMode": true, "mainVersionSW": "03.16.14", "mainVersionHW": "00.00.01", "mainId": "6700116", "mainReference": "25170010", "keyVersionSW": "01.08.04", "zigbeeVersionSW": "01.01.00", "keyVersionHW": "00.00.01", "keyVersionStack": "04.02.06", "keyReference": "25170020", "zigbeeReference": "25170030", "oryxVersion": "2.1.8-10.02", "bootReference": "P25170011", "bootVersion": "01.00.10", "TYDOM.dat": 0, "config.json": 0, "mom.json": 0, "gateway.dat": 0, "bdd.json": 11, "collect.json": 32, "groups.json": 10, "mom_api.json": 0, "scenario.json": 0, "site.json": 46, "bdd_mig.json": 0, "info_mig.json": 0, "info_col.json": 1, "absence.json": 0, "anticip.json": 0, "trigger.json": 0, "bioclim.json": 0, "data_config.json": 2, "urlMediation": "mediation.tydom.com", "pltRegistered": true, "updateAvailable": false, "passwordEmpty": false, "maintenance": {"id": "ffffffffffffffffffffffffffffffff"}, "geoloc": {"longitude": 16583383, "latitude": 48181271}, "clock": {"clock": "2024-05-27T11:47:57+02:00", "source": "ntp", "timezone": 60, "summerOffset": "ON"}, "moments": {"suspend": {"to": 0}}, "local_claim": {"status": "CLOSE", "lastAccess": "2014-01-01T00:04:12Z"}, "weather": {"outTempSrc": {"devId": null, "epId": null}, "weatherSrc": {"devId": null, "epId": null}}, "protocols": [{"protocol": "X3D", "available": true, "installed": true, "ready": true, "status": "running", "installStatus": "idle"}, {"protocol": "ZIGBEE", "available": true, "installed": true, "ready": true, "status": "running", "installStatus": "idle"}, {"protocol": "X3DV", "available": false}, {"protocol": "PltService", "available": false}, {"protocol": "HTTP", "available": true, "installed": true, "ready": true, "status": "running", "installStatus": "idle"}]}

### Reproduction steps

1.go to my Thermostat X3D
2.turn off heating
3.this warning is displayed 
4. in the tydom home App the heating is turned off, but on HA the heating is still enabled and active

### Debug logs

```text
-
```

**Comment by CyrilP** [comment]
Hello, 
the message {"mode": "STOP", "support": ["STOP", "HEATING"]} is probably an event message which is not handled by the integration because it wasn't needed yet but it can be improved.

for the heating status, can you please : 
- set the integration in debug mode
- restart home assistant
- turn off debug mode on the integration
- get the logs and send them to me (redact username/password/macaddress if needed)

**Comment by AlexanderTurnowsky** [comment]
great, yes i will do it, with both start and stop heating, give 1-2 days to provide you with logs.

**Comment by AlexanderTurnowsky** [comment]
sorry it took longer but here is the debug log now. I strated heating via the X3D, turned it off afterwards and after a while also turned the heating off in HA (as it was not updated).
[home-assistant_deltadore_tydom_2024-06-06T08-10-57.186Z.log](https://github.com/user-attachments/files/15609652/home-assistant_deltadore_tydom_2024-06-06T08-10-57.186Z.log)

**Comment by CyrilP** [comment]
I've just published a new test release with a refresh of the values when an event is receives.
can you give it a try ? the pre-release is called : v0.11-alpha

**Comment by AlexanderTurnowsky** [comment]
tried it but it looks like there is still something in:
Turned on all is working fine. Also the Heating is turned on in HA. The temperature will be updated. 
When turning it off again this will not be syned to HA and a error message comes up in HA.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant
Quelle: custom_components/deltadore_tydom/tydom/tydom_client.py:271
Integration: Delta Dore TYDOM (Dokumentation, Probleme)
Erstmals aufgetreten: 12:39:36 (1 Vorkommnisse)
Zuletzt protokolliert: 12:39:36

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 224, in async_connect
    response = await session.request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1102, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1005, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 223, in async_connect
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.12/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/deltadore_tydom/hub.py", line 287, in ping
    await self._tydom_client.ping()
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 460, in ping
    await self.send_message(method=req, msg=msg_type)
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 411, in send_message
    await self.send_bytes(a_bytes)
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 384, in send_bytes
    self._connection = await self.async_connect()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/deltadore_tydom/tydom/tydom_client.py", line 271, in async_connect
    raise TydomClientApiClientCommunicationError(
custom_components.deltadore_tydom.tydom.tydom_client.TydomClientApiClientCommunicationError: Timeout error fetching information

and after the error again an warning:
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.deltadore_tydom
Quelle: custom_components/deltadore_tydom/tydom/MessageHandler.py:164
Integration: Delta Dore TYDOM (Dokumentation, Probleme)
Erstmals aufgetreten: 12:35:27 (19 Vorkommnisse)
Zuletzt protokolliert: 12:39:57

Unknown message type received

i will provide you in a few minutes with a debug logging.

**Comment by CyrilP** [comment]
I see why it doesn't show it off. 
the code expects hvacMode to be OFF but only  thermicLevel is set to OFF.
Climate entity is giving me headache with all the different hardware behaving differently.
I'll try to fix that

**Comment by jefG-dlw** [comment]
i got the same issue, any update on this bug?

**Comment by wizmul** [comment]
Hi, I'm also experiencing the same issue on Home Assistant. Could you please fix it? Thanks.

**Comment by wizmul** [comment]
> > Can you please send full debug logs ?
> 
> Salut, Le fichier de debug ci-dessous. À 19h31mn56 ordre d'allumage réussi À 19h31mn59 ordre d'extinction envoyé avec message d'erreur. Problème déjà identifié au dessus avec le thermic level en off mais pas le hvac mode. Tydom avec tybox 137 et récepteur rf640
> 
> [home-assistant_deltadore_tydom_2025-10-01T17-33-33.102Z.log](https://github.com/user-attachments/files/22645924/home-assistant_deltadore_tydom_2025-10-01T17-33-33.102Z.log)

Bonsoir,
Pensez vous que ce bug peut être résolu ?

**Comment by Sleinous** [comment]
Bonjour @wizmul,

Merci pour le journal. Les changements intégrés depuis ton test corrigent maintenant l’interprétation de `thermicLevel=STOP` et `authorization=STOP` pour les thermostats de zone comme le TYBOX 137 / RF640.

Il restait toutefois un second problème : l’évènement `/events/home/hvac` était encore signalé comme un type de message inconnu et ne déclenchait pas explicitement l’actualisation des appareils. Une correction dédiée est maintenant disponible ici :

https://github.com/Sleinous/hass-deltadore-tydom-component/tree/fix/issue-92-home-hvac-events

Pour la tester, il suffit de remplacer le fichier suivant puis de redémarrer Home Assistant :

- `custom_components/deltadore_tydom/tydom/MessageHandler.py`

Peux-tu ensuite tester les opérations suivantes avec la journalisation de débogage activée ?

- chauffage → arrêt depuis Home Assistant ;
- arrêt → chauffage depuis Home Assistant ;
- arrêt puis remise en chauffage depuis l’application Tydom ou le TYBOX.

Il faudrait vérifier que l’état est correctement actualisé dans Home Assistant et que l’avertissement concernant `/events/home/hvac` a disparu. Peux-tu également joindre le nouveau journal afin que nous puissions confirmer définitivement la correction du ticket ?
